export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="agnoster"

plugins=(git z node npm zsh-syntax-highlighting zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# Stop auto change of directory from zsh
unsetopt AUTO_CD

# Lang exports
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# History config
setopt HIST_IGNORE_ALL_DUPS
export HISTFILE="$HOME/.zsh_history"
export HISTORY_IGNORE="(ls|cd|clear|z)"
export HISTSIZE=999999999
export SAVEHIST=$HISTSIZE

# bind ctrl-space to choose zsh autosuggestions
bindkey '^ ' autosuggest-accept

# Add volta to path
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# Add bin to path, should eventually remove this and use dotfiles bin
export PATH="/usr/local/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Golang
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

# Linux specific setup
if [[ "$(uname)" == "Linux" ]]; then
  # Turn caps lock into escape
  setxkbmap -option caps:escape
  # Disable PgUp and PgDown, they have a really annoying position on my laptop
  # xmodmap -pke to list all keycodes
  xmodmap -e 'keycode 112 = '
  xmodmap -e 'keycode 117 = '
  # Export term for better colors in TMUX
  export TERM='screen-256color'
fi

# OSX specific setup
if [[ "$(uname)" == "Darwin" ]]; then
  export ZSH_DISABLE_COMPFIX=true
fi

# Disable some git commands for Starship in KLAPP
if [[ "$(pwd)" =~ klarna-app ]]; then
  export STARSHIP_CONFIG=~/.config/starship-klapp.toml
fi

# Add bin to path, should eventually remove this and use dotfiles bin
export PATH="/usr/local/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Aws region
export AWS_REGION=eu-west-1
export AWS_DEFAULT_REGION=eu-west-1

# Set nvim as default editor
export VISUAL=nvim
export EDITOR="$VISUAL"

# GPG
export GPG_TTY=$(tty)

# Aliases
alias vim=nvim
alias vi=nvim
alias gs="git status"
alias open="gio open"
alias tree="/usr/local/bin/tree -I node_modules"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# fzf search with ripgrep
export FZF_DEFAULT_COMMAND="rg --files --hidden -i --ignore-file '~/.ignore'"
export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
# Removes username@host from the terminal prompt
# prompt_context() {}

# Only show current dir not entire path
# prompt_dir() { prompt_segment blue black '%c' }

# export TERM='screen-256color'

# I always want TMUX to run
_not_inside_tmux() {
  [[ -z "$TMUX" ]]
}

ensure_tmux_is_running() {
  if _not_inside_tmux; then
    tat
  fi
}
ensure_tmux_is_running

# Klarna
eval "$(direnv hook $SHELL)"

function aws-profile() {
  export AWS_PROFILE="$(grep '\[.*\]' ~/.aws/credentials | tr -d '[-]' | fzf)"
}

# enable zmv
autoload zmv
fpath=($fpath "/home/conner/.zfunctions")


# zsh functions
fpath+=${ZDOTDIR:-~}/.zsh_functions

# Set color of autocomplete text
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=240'

export XDG_CONFIG_HOME=$HOME/.config

# Set starship ZSH as a prompt
eval "$(starship init zsh)"

alias luamake=/home/cnr/lua-language-server/3rd/luamake/luamake
