export ZSH="$HOME/.oh-my-zsh"

# plugins=(git keychain gpg-agent z node npm zsh-syntax-highlighting zsh-autosuggestions)
plugins=(git keychain gpg-agent z node npm zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

function toggle_theme() {
  if [[ $THEME == "dark" ]]; then
    tmux source-file ~/code/creativecreature/dotfiles/terminal/tmux/light-theme
    kitty +kitten themes --reload-in=all Catppuccin Kitty Latte
    export THEME="light"
  else
    tmux source-file ~/code/creativecreature/dotfiles/terminal/tmux/dark-theme
    kitty +kitten themes --reload-in=all dark
    export THEME="dark"
  fi
}

# Stop auto change of directory from zsh
unsetopt AUTO_CD

# Lang exports
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# History config
setopt HIST_IGNORE_ALL_DUPS
export HISTFILE="$HOME/.zsh_history"
export HISTORY_IGNORE="(ls|cd|clear|z)"
export HISTSIZE=999999999
export SAVEHIST=$HISTSIZE

# bind ctrl-space to choose zsh autosuggestions
bindkey '^ ' autosuggest-accept

# Add volta to path
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# Golang
export GOROOT=$(go env GOROOT)
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# Linux specific setup
if [[ "$(uname)" == "Linux" ]]; then
  # Turn caps lock into escape
  setxkbmap -option caps:escape
  # Disable PgUp and PgDown, they have a really annoying position on my laptop
  # xmodmap -pke to list all keycodes
  xmodmap -e 'keycode 112 = '
  xmodmap -e 'keycode 117 = '
	alias open="gio open"
fi

# OSX specific setup
if [[ "$(uname)" == "Darwin" ]]; then
  export ZSH_DISABLE_COMPFIX=true
fi

# Add bin to path, should eventually remove this and use dotfiles bin
export PATH="/usr/local/bin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Aws region
export AWS_REGION=eu-west-1
export AWS_DEFAULT_REGION=eu-west-1

# Set nvim as default editor
export VISUAL=nvim
export EDITOR="$VISUAL"

# GPG
export GPG_TTY=$(tty)

# Aliases
alias vim=nvim
alias vi=nvim
alias gs="git status"
alias tree="/usr/local/bin/tree -I node_modules"
alias spotify=spt

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# fzf search with ripgrep
export FZF_DEFAULT_COMMAND="rg --files --hidden -i --ignore-file '~/.ignore'"
export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND

export TERM='xterm-kitty'

# Helper to detect if we are running tmux
_not_inside_tmux() {
  [[ -z "$TMUX" ]]
}

# I always want TMUX to run
ensure_tmux_is_running() {
  if _not_inside_tmux; then
    tat
  fi
}
ensure_tmux_is_running

# enable zmv
autoload zmv
fpath=($fpath "/home/conner/.zfunctions")

# zsh functions
fpath+=${ZDOTDIR:-~}/.zsh_functions

# Set color of autocomplete text
# export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#5C5F77'

export XDG_CONFIG_HOME=$HOME/.config

# Set starship ZSH as a prompt
eval "$(starship init zsh)"

# direnv needs to be hooked into the shell to work properly
eval "$(direnv hook $SHELL)"

# Setup github copilot cli aliases
eval "$(github-copilot-cli alias -- "$0")"
