#!/bin/bash
docker build -t daws -f ./Dockerfile.aws .
docker run --rm -it -v "$PWD:/app" -w /app  -e AWS_DEFAULT_REGION=eu-west-1 -e AWS_REGION=eu-west-1 --entrypoint /usr/local/bin/aws daws $@



# vim: ft=sh
